"""remove query and connection_id from report_columns

Revision ID: 72618d6beea6
Revises: 
Create Date: 2026-02-11 11:02:17.101617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72618d6beea6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_columns', 'query')
    op.drop_column('report_columns', 'connection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_columns', sa.Column('connection_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('report_columns', sa.Column('query', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
